project needed upgrade.
error: no such package: 'jquery-ui'
error: no such package: 'GAnalytics'

upgraded to latest version to get rid of all meteor startup-errors.

Still not running.